### PR TITLE
CMake Improvements

### PR DESCRIPTION
**Pull request by sergiosvieira**
Hi,

I did some improvements on CMake files. I created a cmake file to generate a winfunc library and link this library on tests files.

with regards,
sergio vieira

### CODE REVIEW

**Comment by vichargrave** [comment]
Sorry for the very, very late reply on this.  But what version of Windows and VC++ are you testing this with?

**Comment by jonjoliver** [comment]
Hi Sergio
Thank you.
I have reviewed this.
I am concerned about changes to CmakeLists.txt
Such as "cmake_minimum_required(VERSION 3.6)"
This may effect existing users in Linux / Mac / ... etc

Also I have concerns that these changes are fully backwards compatible on MS VS
Can we put this in a Windows_VS2017 directory ?
And have if statements so the the cmake_minimum_required only applies to VS2017

Cheers
jono

**Comment by Nirusu** [comment]
Yeah, could we get some files for newer Visual Studio versions, please? Downloading and providing a tool chain from VS 2008 is bothersome and while upgrading the .sln files by myself is possible of course, having newer ones out of the box would be great and would save us a couple of additional steps, as listed in the README.Windows.

Would be great if you could push newer ones to the repo!

**Comment by jonjoliver** [comment]
We have created a different environment
   MINGW for windows build
   New python package at https://pypi.org/project/py-tlsh/
So I think this pull request is out of date.

If there are components that resolve parts - then please suggest in a new Pull Request
Could I ask you split pull requests into smaller parts?

**Pull request closed without merging**
