### PR TITLE
Add a simple Travis CI file

### PR DESCRIPTION
**Pull request by sschuberth**
This is useful to check whether PRs break the build or the tests.

For this to work you need to sign up with [Travis CI](https://travis-ci.org/) first. When done, it would probably also make sense to convert the README file to markdown format and add a build badge for the master branch to it.

### CODE REVIEW

**Comment by Scott4man** [comment]
Hi,

Give me some time to look into this before I pick up travis.yml

Best Regards,
Scott

**Comment by sschuberth** [comment]
In case you'd like to know how such a build for TLSH on Travis CI looks like, see e.g. https://travis-ci.org/sschuberth/tlsh/builds/78579956.

**Comment by sschuberth** [comment]
@Scott4man Any update on this?

**Comment by Scott4man** [comment]
Hi Sebastian,

Thanks for the reminder and your contribution.  I pulled in your merge.

Best,
Scott

**Comment by sschuberth** [comment]
Thanks Scott. It [does not look like](https://travis-ci.org/trendmicro/tlsh/) as if you've also enabled Travis CI looking at this project. Mind doing so, so that PRs get actually tested?

**Comment by Scott4man** [comment]
Hi Sebastian, thanks for tracking this.

I have done the authorization, but the link
<https://travis-ci.org/trendmicro/tlsh/> does not show any builds.  Do I
need to do something else to schedule the builds?

Scott

**Comment by sschuberth** [comment]
Hi Scott,

AFAIK there currently is no easy way to trigger an *initial* Travis build without pushing a new commit. For existing builds / PRs you can retrigger [manually](http://stackoverflow.com/a/17624403/1127485) or [though the API](http://docs.travis-ci.com/user/triggering-builds/).

But as I wanted to create a PR that turns the README into markdown, I'll simply do that, and you should be able to see the build in action.

**Comment by sschuberth** [comment]
See https://github.com/trendmicro/tlsh/pull/10 for how Travis CI tests the PR. Once the PR is merged an the `master` branch is updated, you should also see the build badge linked from the top of the README file to turn from *unknown* / gray to *passing* / green.

**Pull request merged**
